name: popcode_challenge_swapi
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Animations
  lottie: ^1.0.1

  # Storage
  hive: ^2.0.2
  hive_flutter: ^1.0.0

  # Route management
  fluro: ^2.0.3

  # Http client
  dio: ^4.0.0

  # Notfications
  overlay_support: ^1.2.0

  # Dependency injection
  get_it: ^6.0.0

  # Data parse
  json_annotation: ^4.0.0

  # Equality Comparisons
  equatable: ^2.0.0

  # State management
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  
  # State network
  connectivity: ^3.0.3
  
  # Metadata
  after_layout: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Storage
  hive_generator: ^1.0.1

  # State management
  mobx_codegen: ^2.0.1+2

  # Data parse
  json_serializable: ^4.0.0

  # Dependency injection
  injectable_generator: ^1.2.2

  # Code generation
  build_runner: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/ui/assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: lib/ui/assets/fonts/Poppins/Poppins-Light.ttf
        - asset: lib/ui/assets/fonts/Poppins/Poppins-Italic.ttf
        - asset: lib/ui/assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: lib/ui/assets/fonts/Poppins/Poppins-Regular.ttf
  assets:
    - lib/ui/assets/animations/bb8-loading.json
    - lib/ui/assets/images/logo-app-dark.png
    - lib/ui/assets/images/logo-app-light.png
    - lib/ui/assets/images/1.png
    